/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { LoopOnce, LoopRepeat } from 'three';
import { useFrame, useLoader } from '@react-three/fiber';
import { useStore } from '../Store';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';


export const Character = React.memo((props) =>
{
    const { nodes, materials } = useLoader(GLTFLoader, '/assets/models/character.glb')
    const groupRef = useRef();
    const { actions, mixer } = useStore((state) => state);
    // working
    // const idleAnimation = useFBX('/assets/animations/idle.fbx');
    // console.log(idleAnimation);
    // idleAnimation['animations'][0].name='idle';
    // const {actions}=useAnimations(idleAnimation['animations'],groupRef);
    // useEffect(() =>
    // {
    //     actions['idle'].play();
    // })
    const idleAnimation = useGLTF('/assets/animations/idle.glb').animations
    // useFBX('/assets/animations/idle.fbx').animations
    idleAnimation[0].name = 'idle';
    const jumpAnimation = useGLTF('/assets/animations/jumping.glb').animations
    jumpAnimation[0].name = 'jump';
    const runningJumpAnimation = useGLTF('/assets/animations/runningJump.glb').animations
    runningJumpAnimation[0].name = 'runningJump';
    const runAnimation = useGLTF('/assets/animations/running.glb').animations
    runAnimation[0].name = 'run';
    const walkAnimation = useGLTF('/assets/animations/walking.glb').animations
    walkAnimation[0].name = 'walk';
    const attackAnimation = useGLTF('/assets/animations/attack.glb').animations
    attackAnimation[0].name = 'attack';
    const crouchAnimation = useGLTF('/assets/animations/crouch.glb').animations;
    crouchAnimation[0].name = 'crouch';
    //Emotes
    const flairAnimation = useGLTF('/assets/animations/flair.glb').animations;
    flairAnimation[0].name = 'flair'

    const houseDancingAnimation = useGLTF('/assets/animations/houseDance.glb').animations;
     
    houseDancingAnimation[0].name = 'houseDancing'
    const breakDance1990Animation = useGLTF('/assets/animations/crouch.glb').animations;
    breakDance1990Animation[0].name = 'breakDance1990'
    const gangnamStyleAnimation = useGLTF('/assets/animations/gangnamStyle.glb').animations;
    gangnamStyleAnimation[0].name = ' gangnamStyle'
    const stylishFlipAnimation = useGLTF('/assets/animations/stylishFlip.glb').animations;
    stylishFlipAnimation[0].name = 'stylishFlip'
    useEffect(() =>
    {
        actions['idle'] = mixer.clipAction(idleAnimation[0], groupRef.current)
        actions['idle'].loop = LoopRepeat;
        actions['jump'] = mixer.clipAction(jumpAnimation[0], groupRef.current)
        actions['jump'].loop = LoopOnce;
        actions['runningJump'] = mixer.clipAction(runningJumpAnimation[0], groupRef.current)
        actions['runningJump'].loop = LoopOnce;
        actions['run'] = mixer.clipAction(runAnimation[0], groupRef.current)
        actions['run'].loop = LoopOnce;
        actions['walk'] = mixer.clipAction(walkAnimation[0], groupRef.current)
        actions['walk'].loop = LoopOnce;
        actions['attack'] = mixer.clipAction(attackAnimation[0], groupRef.current)
        actions['attack'].loop = LoopOnce;
        actions['crouch'] = mixer.clipAction(crouchAnimation[0], groupRef.current)
        actions['crouch'].loop = LoopRepeat;
        actions['stylishFlip'] = mixer.clipAction(stylishFlipAnimation[0], groupRef.current);
        actions['stylishFlip'].loop = LoopOnce;
        actions['gangnamStyle'] = mixer.clipAction(gangnamStyleAnimation[0], groupRef.current);
        actions['gangnamStyle'].loop = LoopOnce;
        actions['breakDance1990'] = mixer.clipAction(breakDance1990Animation[0], groupRef.current);
        actions['breakDance1990'].loop = LoopOnce;
        actions['houseDancing'] = mixer.clipAction(houseDancingAnimation[0], groupRef.current);
        actions['houseDancing'].loop = LoopOnce;
        actions['flair'] = mixer.clipAction(flairAnimation[0], groupRef.current);
        actions['flair'].loop = LoopOnce;
        actions['idle'].play()
    }, [actions, mixer, idleAnimation, jumpAnimation, runningJumpAnimation, runAnimation, walkAnimation, attackAnimation])
    useFrame((state, delta) => { mixer.update(delta); });
    return (

        <group {...props} dispose={null} scale={.5} ref={groupRef} position={[0, 1, 0]} >
            <group name="Scene">
                <group name="Armature" userData={{ name: 'Armature' }}>
                    <primitive object={nodes.Hips} />
                    <skinnedMesh
                        name="EyeLeft"
                        geometry={nodes.EyeLeft.geometry}
                        material={materials.Wolf3D_Eye}
                        skeleton={nodes.EyeLeft.skeleton}
                        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
                        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
                        userData={{ targetNames: ['mouthOpen', 'mouthSmile'], name: 'EyeLeft' }}
                    />
                    <skinnedMesh
                        name="EyeRight"
                        geometry={nodes.EyeRight.geometry}
                        material={materials.Wolf3D_Eye}
                        skeleton={nodes.EyeRight.skeleton}
                        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
                        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
                        userData={{ targetNames: ['mouthOpen', 'mouthSmile'], name: 'EyeRight' }}
                    />
                    <skinnedMesh
                        name="Wolf3D_Head"
                        geometry={nodes.Wolf3D_Head.geometry}
                        material={materials.Wolf3D_Skin}
                        skeleton={nodes.Wolf3D_Head.skeleton}
                        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
                        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
                        userData={{ targetNames: ['mouthOpen', 'mouthSmile'], name: 'Wolf3D_Head' }}
                    />
                    <skinnedMesh
                        name="Wolf3D_Teeth"
                        geometry={nodes.Wolf3D_Teeth.geometry}
                        material={materials.Wolf3D_Teeth}
                        skeleton={nodes.Wolf3D_Teeth.skeleton}
                        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
                        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
                        userData={{ targetNames: ['mouthOpen', 'mouthSmile'], name: 'Wolf3D_Teeth' }}
                    />
                    <skinnedMesh
                        name="Wolf3D_Hair"
                        geometry={nodes.Wolf3D_Hair.geometry}
                        material={materials.Wolf3D_Hair}
                        skeleton={nodes.Wolf3D_Hair.skeleton}
                        userData={{ name: 'Wolf3D_Hair' }}
                    />
                    <skinnedMesh
                        name="Wolf3D_Body"
                        geometry={nodes.Wolf3D_Body.geometry}
                        material={materials.Wolf3D_Body}
                        skeleton={nodes.Wolf3D_Body.skeleton}
                        userData={{ name: 'Wolf3D_Body' }}
                    />
                    <skinnedMesh
                        name="Wolf3D_Outfit_Bottom"
                        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
                        material={materials.Wolf3D_Outfit_Bottom}
                        skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
                        userData={{ name: 'Wolf3D_Outfit_Bottom' }}
                    />
                    <skinnedMesh
                        name="Wolf3D_Outfit_Footwear"
                        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
                        material={materials.Wolf3D_Outfit_Footwear}
                        skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
                        userData={{ name: 'Wolf3D_Outfit_Footwear' }}
                    />
                    <skinnedMesh
                        name="Wolf3D_Outfit_Top"
                        geometry={nodes.Wolf3D_Outfit_Top.geometry}
                        material={materials.Wolf3D_Outfit_Top}
                        skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
                        userData={{ name: 'Wolf3D_Outfit_Top' }}
                    />
                </group>
            </group>
        </group>


    )
}
)

useLoader.preload(GLTFLoader, '/assets/models/character.glb')
useGLTF.preload('/assets/animations/idle.glb')
useGLTF.preload('/assets/animations/jumping.glb')
useGLTF.preload('/assets/animations/runningJump.glb')
useGLTF.preload('/assets/animations/running.glb')
useGLTF.preload('/assets/animations/walking.glb')
useGLTF.preload('/assets/animations/attack.glb')
useGLTF.preload('/assets/animations/crouch.glb')