/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useAnimations, useFBX, useGLTF } from '@react-three/drei'
import { AnimationMixer } from 'three';
import { useFrame } from '@react-three/fiber';

export function Character (props)
{


    const { nodes, materials } = useGLTF('/assets/models/character.glb')
    const groupRef = useRef();
    // working
    // const idleAnimation = useFBX('/assets/animations/idle.fbx');
    // console.log(idleAnimation);
    // idleAnimation['animations'][0].name='idle';
    // const {actions}=useAnimations(idleAnimation['animations'],groupRef);
    // useEffect(() =>
    // {
    //     actions['idle'].play();
    // })
    const idleAnimation = useFBX('/assets/animations/idle.fbx').animations
    idleAnimation[0].name = 'idle';
    console.log(idleAnimation[0]);
    const mixer =  new AnimationMixer()
    useEffect(() =>
    {
        const action = mixer.clipAction(idleAnimation[0], groupRef.current)
        action.play()
    }, [])
    useFrame((state, delta) => { mixer.update(delta); });
    return (
        <group {...props} dispose={null} scale={.5} ref={groupRef} >
            <group name="Scene">
                <group name="Armature" userData={{ name: 'Armature' }}>
                    <primitive object={nodes.Hips} />
                    <skinnedMesh
                        name="EyeLeft"
                        geometry={nodes.EyeLeft.geometry}
                        material={materials.Wolf3D_Eye}
                        skeleton={nodes.EyeLeft.skeleton}
                        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
                        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
                        userData={{ targetNames: ['mouthOpen', 'mouthSmile'], name: 'EyeLeft' }}
                    />
                    <skinnedMesh
                        name="EyeRight"
                        geometry={nodes.EyeRight.geometry}
                        material={materials.Wolf3D_Eye}
                        skeleton={nodes.EyeRight.skeleton}
                        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
                        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
                        userData={{ targetNames: ['mouthOpen', 'mouthSmile'], name: 'EyeRight' }}
                    />
                    <skinnedMesh
                        name="Wolf3D_Head"
                        geometry={nodes.Wolf3D_Head.geometry}
                        material={materials.Wolf3D_Skin}
                        skeleton={nodes.Wolf3D_Head.skeleton}
                        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
                        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
                        userData={{ targetNames: ['mouthOpen', 'mouthSmile'], name: 'Wolf3D_Head' }}
                    />
                    <skinnedMesh
                        name="Wolf3D_Teeth"
                        geometry={nodes.Wolf3D_Teeth.geometry}
                        material={materials.Wolf3D_Teeth}
                        skeleton={nodes.Wolf3D_Teeth.skeleton}
                        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
                        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
                        userData={{ targetNames: ['mouthOpen', 'mouthSmile'], name: 'Wolf3D_Teeth' }}
                    />
                    <skinnedMesh
                        name="Wolf3D_Hair"
                        geometry={nodes.Wolf3D_Hair.geometry}
                        material={materials.Wolf3D_Hair}
                        skeleton={nodes.Wolf3D_Hair.skeleton}
                        userData={{ name: 'Wolf3D_Hair' }}
                    />
                    <skinnedMesh
                        name="Wolf3D_Body"
                        geometry={nodes.Wolf3D_Body.geometry}
                        material={materials.Wolf3D_Body}
                        skeleton={nodes.Wolf3D_Body.skeleton}
                        userData={{ name: 'Wolf3D_Body' }}
                    />
                    <skinnedMesh
                        name="Wolf3D_Outfit_Bottom"
                        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
                        material={materials.Wolf3D_Outfit_Bottom}
                        skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
                        userData={{ name: 'Wolf3D_Outfit_Bottom' }}
                    />
                    <skinnedMesh
                        name="Wolf3D_Outfit_Footwear"
                        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
                        material={materials.Wolf3D_Outfit_Footwear}
                        skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
                        userData={{ name: 'Wolf3D_Outfit_Footwear' }}
                    />
                    <skinnedMesh
                        name="Wolf3D_Outfit_Top"
                        geometry={nodes.Wolf3D_Outfit_Top.geometry}
                        material={materials.Wolf3D_Outfit_Top}
                        skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
                        userData={{ name: 'Wolf3D_Outfit_Top' }}
                    />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/assets/models/character.glb')
