/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Digital screen official (https://sketchfab.com/ck212575)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/low-poly-forest-1-e7bb0600ee7c47a9aadf5598861837aa
Title: low poly forest 1
*/


import { useGLTF } from '@react-three/drei'
import { useEffect, useRef } from 'react';
import { useStore } from '../Store';
import { usePlane } from '@react-three/cannon';

export function Map2 (props)
{
    const { nodes, materials } = useGLTF('/assets/models/map2.glb')
    const groundRef = useRef()
    const groundObject = useStore((state) => state.groundObject)

    // Add physics ground plane
    const [ref] = usePlane(() => ({
        rotation: [-Math.PI / 2, 0, 0],
        position: [0, .5, 0],
        type: 'Static',
        material: 'ground'
    }))

    useEffect(() => {
        const id = groundRef.current.id
        groundObject[id] = groundRef.current
        return () => {
            delete groundObject[id]
        }
    }, [groundObject])

    return (
        <>
 <group {...props} dispose={null}>
            {/* Physics ground plane */}
            <mesh ref={ref} visible={false}>
                <planeGeometry args={[1000, 1000]} />
            </mesh>

</group>
        <group {...props} dispose={null} ref={groundRef}>
            <group name="Sketchfab_Scene">
                <group
                    name="Sketchfab_model"
                    rotation={[-Math.PI / 2, 0, 0]}
                    userData={{ name: 'Sketchfab_model' }}>
                    <group
                        name="low_poly_forest_1objcleanermaterialmergergles"
                        userData={{ name: 'low poly forest 1.obj.cleaner.materialmerger.gles' }}>
                        <mesh
                            name="Object_2"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_2.geometry}
                            material={materials.Material}
                            userData={{ name: 'Object_2' }}
                        />
                        <mesh
                            name="Object_3"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_3.geometry}
                            material={materials.Material}
                            userData={{ name: 'Object_3' }}
                        />
                        <mesh
                            name="Object_4"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_4.geometry}
                            material={materials.Material}
                            userData={{ name: 'Object_4' }}
                        />
                        <mesh
                            name="Object_5"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_5.geometry}
                            material={materials.Material}
                            userData={{ name: 'Object_5' }}
                        />
                    </group>
                </group>
            </group>
        </group>
        </>

    )
}

useGLTF.preload('/assets/models/map2.glb')
